const illnessMap = {
    "malaria": "Artemisinin-based combination therapy (ACT)",
    "flu": "Rest, fluids, and paracetamol",
    "typhoid": "Antibiotics (consult doctor)",
    "cancer": "Chemotherapy, radiotherapy, or surgery (consult oncologist)",
    "diabetes": "Insulin therapy and lifestyle management",
    "hypertension": "Antihypertensive drugs (consult doctor)",
    "asthma": "Inhaled corticosteroids and bronchodilators",
    "tuberculosis": "Combination of antibiotics (consult doctor)",
    "pneumonia": "Antibiotics and supportive care",
    "arthritis": "Pain relievers, anti-inflammatory drugs, physiotherapy",
    "migraine": "Pain relievers, triptans, lifestyle adjustments",
    "epilepsy": "Antiepileptic drugs (AEDs)",
    "depression": "Antidepressants and psychotherapy",
    "anxiety": "Therapy, relaxation techniques, medication if needed",
    "stroke": "Emergency care, clot-busting drugs, rehabilitation",
    "heart disease": "Lifestyle changes, statins, beta-blockers",
    "kidney failure": "Dialysis or transplant",
    "liver cirrhosis": "Lifestyle changes, medications, possible transplant",
    "bronchitis": "Rest, fluids, bronchodilators if needed",
    "eczema": "Topical corticosteroids, moisturizers",
    "psoriasis": "Topical treatments, phototherapy, systemic drugs",
    "cholera": "Rehydration therapy, antibiotics",
    "dengue": "Supportive care, fluids, pain relief",
    "hepatitis B": "Antiviral medication, monitoring",
    "hepatitis C": "Direct-acting antivirals",
    "HIV/AIDS": "Antiretroviral therapy (ART)",
    "COVID-19": "Supportive care, antivirals, vaccination",
    "measles": "Supportive care, vitamin A",
    "mumps": "Supportive care, pain relief",
    "rubella": "Supportive care",
    "whooping cough": "Antibiotics, supportive care",
    "polio": "Supportive care, rehabilitation",
    "yellow fever": "Supportive care, vaccination prevention",
    "rabies": "Post-exposure prophylaxis, vaccination",
    "tetanus": "Antitoxin, antibiotics, supportive care",
    "diphtheria": "Antitoxin, antibiotics",
    "scarlet fever": "Antibiotics",
    "syphilis": "Penicillin",
    "gonorrhea": "Antibiotics",
    "chlamydia": "Antibiotics",
    "herpes simplex": "Antiviral medication",
    "shingles": "Antiviral medication, pain relief",
    "chickenpox": "Supportive care, antivirals if severe",
    "ulcer": "Antacids, proton pump inhibitors",
    "gastritis": "Antacids, proton pump inhibitors",
    "appendicitis": "Surgery",
    "tonsillitis": "Antibiotics if bacterial, supportive care",
    "sinusitis": "Decongestants, antibiotics if bacterial",
    "otitis media": "Antibiotics, pain relief",
    "conjunctivitis": "Antibiotics if bacterial, supportive care",
    "glaucoma": "Eye drops, surgery",
    "cataract": "Surgery",
    "anemia": "Iron supplements, blood transfusion if severe",
    "thalassemia": "Blood transfusion, chelation therapy",
    "sickle cell disease": "Pain management, blood transfusion",
    "hemophilia": "Clotting factor replacement",
    "leprosy": "Multi-drug therapy",
    "filariasis": "Antiparasitic drugs",
    "schistosomiasis": "Praziquantel",
    "hookworm": "Antiparasitic drugs",
    "roundworm": "Antiparasitic drugs",
    "tapeworm": "Antiparasitic drugs",
    "pinworm": "Antiparasitic drugs",
    "giardiasis": "Antiparasitic drugs",
    "amoebiasis": "Metronidazole",
    "trichomoniasis": "Metronidazole",
    "ringworm": "Antifungal creams",
    "athlete’s foot": "Antifungal creams",
    "candidiasis": "Antifungal medication",
    "histoplasmosis": "Antifungal medication",
    "cryptococcosis": "Antifungal medication",
    "blastomycosis": "Antifungal medication",
    "aspergillosis": "Antifungal medication",
    "legionnaires’ disease": "Antibiotics",
    "lyme disease": "Antibiotics",
    "rocky mountain spotted fever": "Antibiotics",
    "brucellosis": "Antibiotics",
    "plague": "Antibiotics",
    "anthrax": "Antibiotics",
    "ebola": "Supportive care, experimental antivirals",
    "marburg virus": "Supportive care",
    "lassa fever": "Ribavirin, supportive care",
    "zika virus": "Supportive care",
    "west nile virus": "Supportive care",
    "meningitis": "Antibiotics if bacterial, supportive care",
    "encephalitis": "Antivirals if viral, supportive care",
    "sepsis": "Antibiotics, supportive care",
    "cellulitis": "Antibiotics",
    "abscess": "Drainage, antibiotics",
    "gangrene": "Surgery, antibiotics",
    "osteomyelitis": "Antibiotics, surgery",
    "endocarditis": "Antibiotics, surgery if needed",
    "myocarditis": "Supportive care, antivirals if viral",
    "pericarditis": "Anti-inflammatory drugs",
    "pancreatitis": "Supportive care",
    "hepatitis A": "Supportive care",
    "cirrhosis": "Lifestyle changes, medications",
    "fatty liver disease": "Lifestyle changes",
    "gallstones": "Surgery",
    "kidney stones": "Pain relief, surgery if needed",
    "urinary tract infection": "Antibiotics",
    "prostatitis": "Antibiotics",
    "endometriosis": "Pain relief, hormonal therapy",
    "ovarian cysts": "Monitoring, surgery if needed",
    "fibroids": "Medication, surgery",
    "prostate cancer": "Surgery, radiotherapy, chemotherapy",
    "breast cancer": "Surgery, radiotherapy, chemotherapy",
    "lung cancer": "Surgery, radiotherapy, chemotherapy"
};
